import numpy as np
import cv2 as cv
from image import readImage, writeImagesList, applyGrayscale, applyNoiseRemoval
from segmentation import adaptiveThreshold, lineLevelSegmentation, wordLevelSegmentation
from plot import plotImage, plotHistogram

def main():

    imgFolder = "src/inputImages/"
    imgName = "bookpage"
    imgFormat = ".jpg"
    inputImage = readImage(imgFolder + imgName + imgFormat) # reads image file from folder

    modifiedInputImage = applyGrayscale(inputImage) # filters the image to grayscale
    modifiedInputImage = applyNoiseRemoval(modifiedInputImage) # applies a filter to remove noise
    binaryInputImage = adaptiveThreshold(modifiedInputImage) # applies adaptive threshold to get a binary image

    # plotting binary image
    plotImage(binaryInputImage, "Binary image generated by Adaptive Threshold")

    # applies a segmentation that returns an array of text lines
    lineImages = lineLevelSegmentation(binaryInputImage)
    writeImagesList(lineImages, "src/outputImages/horizontalSegmentation/", ".jpg") # writes the line images on the path folder

    # applies a segmentation on each line that returns an array of words from that text line
    wordsImages = []
    for line in lineImages:
        wordsImages.append(wordLevelSegmentation(line))
    
    # it writes the image files for each words list in wordImages 
    for line in wordsImages:
        writeImagesList(line, "src/outputImages/verticalSegmentation/", ".jpg") # writes the words images on the path folder

if __name__ == "__main__":
    main()